"""feat(user): initial schemas for MVP

Revision ID: 3fe24890dc46
Revises: 
Create Date: 2026-01-28 04:39:33.400631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fe24890dc46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('debit', 'credit', 'cash', name='account_type'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transfer_group_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('income', 'expense', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('merchant', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('manual', 'imported', name='transaction_source'), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash_dedupe', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hash_dedupe', name='uq_transactions_user_hash_dedupe')
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_hash_dedupe'), 'transactions', ['hash_dedupe'], unique=False)
    op.create_index(op.f('ix_transactions_transfer_group_id'), 'transactions', ['transfer_group_id'], unique=False)
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###
    op.create_index("uq_categories_global_name","categories",["name"],unique=True,postgresql_where=sa.text("user_id IS NULL"),)
    op.create_index("uq_categories_user_name","categories",["user_id", "name"],unique=True,postgresql_where=sa.text("user_id IS NOT NULL"),)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_transfer_group_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_hash_dedupe'), table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index("uq_categories_user_name", table_name="categories")
    op.drop_index("uq_categories_global_name", table_name="categories")
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # Manual: drop enum types created by SAEnum(create_type=True)
    op.execute("DROP TYPE IF EXISTS transaction_source")
    op.execute("DROP TYPE IF EXISTS transaction_type")
    op.execute("DROP TYPE IF EXISTS account_type")

